[package]
name = "grothprotocol"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-std = "0.4"
ark-relations = "0.4"
ark-r1cs-std = "0.4"
ark-bls12-381 = "0.4"
ark-ff = "0.4"
ark-crypto-primitives = "0.4"